# .gitlab-ci.yml
stages:
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"
  SERVICE_NAME: "kicker-backend-go"
  DOCKER_IMAGE: "$DOCKER_REGISTRY/$SERVICE_NAME"
  DOCKER_TAG: "$CI_JOB_ID"


build:
  stage: build
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY --username $DOCKER_USERNAME --password-stdin
  image: docker:latest
  services:
    - docker:dind
  script:
    - unset DOCKER_HOST
    - docker build --build-arg GIT_USERNAME=$GIT_USERNAME --build-arg GIT_PASSWORD=$GIT_PASSWORD -t $DOCKER_IMAGE:$DOCKER_TAG .  
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
    - echo $DOCKER_TAG > tag.txt
  artifacts:
    paths:
      - tag.txt


deploy:
  stage: deploy
  only:
    - develop
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY --username $DOCKER_USERNAME --password-stdin
  image: docker:latest
  script:
    - export TAG=$(cat tag.txt)
    - docker images --format "{{.Repository}}:{{.Tag}}" | grep "^$DOCKER_IMAGE:" | xargs -r docker rmi -f
    - docker pull $DOCKER_IMAGE:$TAG
    - docker stop $SERVICE_NAME || true
    - docker rm $SERVICE_NAME || true
    - docker run -d --restart unless-stopped --name $SERVICE_NAME --env-file .env.sample --network kicker -p 4420:8080 $DOCKER_IMAGE:$TAG
  dependencies:
    - build